name: posterr-prod-andre-teixeira

services:

  db:
    image: postgres:16.3
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: posterr_admin
      POSTGRES_PASSWORD: Secr3t!!
      POSTGRES_DB: posterr
    volumes:
       - db:/var/lib/postgresql
    ports:
       - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    build: ./Backend
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 5250:5250
    depends_on:
      - db

  frontend:
    build: ./FrontEnd
    restart: always
    ports:
      - 3000:3000

volumes:
  db:
