version: '3.9'
name: posterr-andre-teixeira

services:

  db:
    image: postgres:16.3
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: posterr_admin
      POSTGRES_PASSWORD: Secr3t!!
      POSTGRES_DB: posterr
    volumes:
       - db:/var/lib/postgresql
    ports:
       - 5432:5432

volumes:
  db:
