using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Posterr.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class Initial : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Username = table.Column<string>(type: "VARCHAR(20)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Publications",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    AuthorId = table.Column<long>(type: "bigint", nullable: false),
                    AuthorUsername = table.Column<string>(type: "text", nullable: false),
                    Content = table.Column<string>(type: "text", nullable: false),
                    PublicationDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "NOW()"),
                    OriginalPostId = table.Column<long>(type: "bigint", nullable: true),
                    OriginalPostAuthorId = table.Column<long>(type: "bigint", nullable: true),
                    OriginalPostAuthorUsername = table.Column<string>(type: "text", nullable: true),
                    OriginalPostContent = table.Column<string>(type: "text", nullable: true),
                    OriginalPostPublicationDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Publications", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Publications_Publications_OriginalPostId",
                        column: x => x.OriginalPostId,
                        principalTable: "Publications",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Publications_Users_AuthorId",
                        column: x => x.AuthorId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "Username" },
                values: new object[,]
                {
                    { 1L, "Mufasa" },
                    { 2L, "Mufasa (spirit)" },
                    { 3L, "Sarabi" },
                    { 4L, "Scar" },
                    { 5L, "Rafiki" },
                    { 6L, "Zazu" },
                    { 7L, "Simba (cub)" },
                    { 8L, "Simba" },
                    { 9L, "Nala (cub)" },
                    { 10L, "Nala" },
                    { 11L, "Timon" },
                    { 12L, "Pumbaa" },
                    { 13L, "Shenzi" },
                    { 14L, "Kamari" },
                    { 15L, "Singers" }
                });

            migrationBuilder.InsertData(
                table: "Publications",
                columns: new[] { "Id", "AuthorId", "AuthorUsername", "Content", "OriginalPostAuthorId", "OriginalPostAuthorUsername", "OriginalPostContent", "OriginalPostId", "OriginalPostPublicationDate", "PublicationDate" },
                values: new object[,]
                {
                    { 1L, 15L, "Singers", "    Nants ingonyama bagithi Baba\r\n    (Sithi uhm ingonyama)\r\n    Nants ingonyama bagithi baba\r\n    (Sithi uhhmm ingonyama, Ingonyama)\r\n    Siyo Nqoba\r\n    (Ingonyama)\r\n    Ingonyama nengw' enamabala\r\n    Ingonyama nengw' enamabala\r\n    Ingonyama nengw' enamabala\r\n    Ingonyama nengw' enamabala", null, null, null, null, null, new DateTime(1994, 7, 9, 12, 0, 0, 0, DateTimeKind.Utc) },
                    { 2L, 4L, "Scar", "Life is not fair, is it, my little friend? While some are born to feast, others spend their lives in the dark, begging for scraps.", null, null, null, null, null, new DateTime(1994, 7, 9, 12, 30, 0, 0, DateTimeKind.Utc) },
                    { 3L, 4L, "Scar", "I answer to no one", null, null, null, null, null, new DateTime(1994, 7, 9, 12, 32, 0, 0, DateTimeKind.Utc) },
                    { 4L, 1L, "Mufasa", "One day, It'll be my son who rules", null, null, null, null, null, new DateTime(1994, 7, 9, 12, 33, 0, 0, DateTimeKind.Utc) },
                    { 5L, 1L, "Mufasa", "Look Simba! Everything the light touches is our kingdom", null, null, null, null, null, new DateTime(1994, 10, 15, 9, 0, 0, 0, DateTimeKind.Utc) },
                    { 6L, 7L, "Simba (cub)", "You rule ALL of that?!", null, null, null, null, null, new DateTime(1994, 10, 15, 9, 0, 10, 0, DateTimeKind.Utc) },
                    { 7L, 1L, "Mufasa", "Yes, but a king's time as ruler rises and falls like the sun. One day Simba, the sun will set on my time here and will rise with you as the new king.", null, null, null, null, null, new DateTime(1994, 10, 15, 9, 0, 15, 0, DateTimeKind.Utc) },
                    { 8L, 7L, "Simba (cub)", "All of this will belong to me?", null, null, null, null, null, new DateTime(1994, 10, 15, 9, 0, 20, 0, DateTimeKind.Utc) },
                    { 9L, 1L, "Mufasa", "It belongs to no one, but will be yours to protect. A great responsibility.", null, null, null, null, null, new DateTime(1994, 10, 15, 9, 0, 25, 0, DateTimeKind.Utc) },
                    { 10L, 7L, "Simba (cub)", "Everything the light touches? Those trees? And the watering hole? And that mountain? And... beyond those shadows?", null, null, null, null, null, new DateTime(1994, 10, 15, 9, 0, 30, 0, DateTimeKind.Utc) },
                    { 11L, 1L, "Mufasa", "You must not go there Simba!", null, null, null, null, null, new DateTime(1994, 10, 15, 9, 0, 35, 0, DateTimeKind.Utc) },
                    { 12L, 7L, "Simba (cub)", "But I thought a king could do whatever he wants! Take any territory!", null, null, null, null, null, new DateTime(1994, 10, 15, 9, 0, 40, 0, DateTimeKind.Utc) },
                    { 13L, 1L, "Mufasa", "While others search for what they can take, a true king searches for what he can give.", null, null, null, null, null, new DateTime(1994, 10, 15, 9, 0, 45, 0, DateTimeKind.Utc) },
                    { 14L, 4L, "Scar", "Go back to your den, Simba. I don't babysit.", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 0, 0, 0, DateTimeKind.Utc) },
                    { 15L, 7L, "Simba (cub)", "Babysit? I'm gonna be the king of Pride Rock! My dad showed me the whole kingdom! Said I'm going to rule it all!", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 0, 5, 0, DateTimeKind.Utc) },
                    { 16L, 4L, "Scar", "Is that so?", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 0, 10, 0, DateTimeKind.Utc) },
                    { 17L, 7L, "Simba (cub)", "Think about it! When I'm king, I'll have to give YOU orders! Tell YOU what to do! How weird is that?", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 0, 15, 0, DateTimeKind.Utc) },
                    { 18L, 4L, "Scar", "You've no idea... So your dad showed you the whole kingdom? Did he show you the shadows beyond the northern borders?", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 0, 20, 0, DateTimeKind.Utc) },
                    { 19L, 7L, "Simba (cub)", "No... He said I can't go there. Ever.", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 0, 25, 0, DateTimeKind.Utc) },
                    { 20L, 4L, "Scar", "And he is absolutely right. An elephant graveyard is no place for a young prince.", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 0, 30, 0, DateTimeKind.Utc) },
                    { 21L, 7L, "Simba (cub)", "An elephant graveyard?! Wow!", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 0, 35, 0, DateTimeKind.Utc) },
                    { 22L, 4L, "Scar", "Oh dear! I've said to much! Well I suppose you'd find out sooner or later, you being... KING... and all...", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 0, 40, 0, DateTimeKind.Utc) },
                    { 23L, 7L, "Simba (cub)", "You've been there???", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 0, 45, 0, DateTimeKind.Utc) },
                    { 24L, 4L, "Scar", "We've all been there! It's no place for a cub. All those roting bones... and burning pools of oozing mud...", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 0, 50, 0, DateTimeKind.Utc) },
                    { 25L, 7L, "Simba (cub)", "Roting bones?! Oozing mud?!", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 0, 55, 0, DateTimeKind.Utc) },
                    { 26L, 4L, "Scar", "Promise me you'll stay away, Simba! Now, you run along. And remember... it's our little secret... your majesty...", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 1, 0, 0, DateTimeKind.Utc) },
                    { 27L, 7L, "Simba (cub)", "Nala! C'mon, we have to go!", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 5, 0, 0, DateTimeKind.Utc) },
                    { 28L, 7L, "Simba (cub)", "I've heard about this place, Nala! The most incredible, amazing! [...] An elephant... GRAVEYARD!", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 7, 0, 0, DateTimeKind.Utc) },
                    { 29L, 9L, "Nala (cub)", "Wow! How far is it?", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 7, 5, 0, DateTimeKind.Utc) },
                    { 30L, 7L, "Simba (cub)", "Not far. Just to the shadows. But don't worry, everyone's been there!", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 7, 10, 0, DateTimeKind.Utc) },
                    { 31L, 9L, "Nala (cub)", "We've never went that far before. What if we get lost?", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 7, 15, 0, DateTimeKind.Utc) },
                    { 32L, 7L, "Simba (cub)", "Relax, Nala! I patroled the entire kingdom this morning with my dad! There's nothing to worry about.", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 7, 20, 0, DateTimeKind.Utc) },
                    { 33L, 6L, "Zazu", "Simba, you can't escape your destiny!", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 20, 30, 0, DateTimeKind.Utc) },
                    { 34L, 7L, "Simba (cub)", "I'm gonna be a mighty king, so enemies beware! [...] Oh, I just can't wait to be king! No one saying do this, no one saying be there, no one saying stop that, no one saying see here!. Free to run around all day, free to do it all my way! Oh, I just can't wait to be king!", null, null, null, null, null, new DateTime(1994, 10, 16, 10, 40, 0, 0, DateTimeKind.Utc) },
                    { 35L, 7L, "Simba (cub)", "This must be it! C'mon!", null, null, null, null, null, new DateTime(1994, 10, 16, 13, 0, 0, 0, DateTimeKind.Utc) },
                    { 36L, 9L, "Nala (cub)", "Simba, we're way beyond the Pride Lands.", null, null, null, null, null, new DateTime(1994, 10, 16, 13, 0, 5, 0, DateTimeKind.Utc) },
                    { 37L, 7L, "Simba (cub)", "We found it Nala! You know what this means?", null, null, null, null, null, new DateTime(1994, 10, 16, 13, 0, 10, 0, DateTimeKind.Utc) },
                    { 38L, 9L, "Nala (cub)", "It means we can go home!", null, null, null, null, null, new DateTime(1994, 10, 16, 13, 0, 15, 0, DateTimeKind.Utc) },
                    { 39L, 7L, "Simba (cub)", "It means they won't treat us like cubs anymore.", null, null, null, null, null, new DateTime(1994, 10, 16, 13, 0, 20, 0, DateTimeKind.Utc) },
                    { 40L, 7L, "Simba (cub)", "I laugh in the face of danger! HAHAHA!", null, null, null, null, null, new DateTime(1994, 10, 16, 13, 5, 30, 0, DateTimeKind.Utc) },
                    { 41L, 13L, "Shenzi", "Now, this is a meal I've waited my whole life for! What an unexpected treat! To eat the son of a king! Mufasa does not rule me!", null, null, null, null, null, new DateTime(1994, 10, 16, 13, 10, 30, 0, DateTimeKind.Utc) },
                    { 42L, 7L, "Simba (cub)", "You can't do anything to me! 'Cause I'm the future king!", null, null, null, null, null, new DateTime(1994, 10, 16, 13, 10, 35, 0, DateTimeKind.Utc) },
                    { 43L, 13L, "Shenzi", "I wonder how all that bravery will taste!", null, null, null, null, null, new DateTime(1994, 10, 16, 13, 10, 40, 0, DateTimeKind.Utc) },
                    { 44L, 6L, "Zazu", "If you do this, you will start a war with Mufasa!", null, null, null, null, null, new DateTime(1994, 10, 16, 13, 10, 50, 0, DateTimeKind.Utc) },
                    { 45L, 13L, "Shenzi", "Hyenas and lions have been at war since the beginning of time! But Mufasa's bloodline will end here!", null, null, null, null, null, new DateTime(1994, 10, 16, 13, 11, 0, 0, DateTimeKind.Utc) },
                    { 46L, 1L, "Mufasa", "If you ever come near my son again...!", null, null, null, null, null, new DateTime(1994, 10, 16, 13, 12, 30, 0, DateTimeKind.Utc) },
                    { 47L, 13L, "Shenzi", "No, Mufasa. Never. Never again.", null, null, null, null, null, new DateTime(1994, 10, 16, 13, 12, 35, 0, DateTimeKind.Utc) },
                    { 48L, 1L, "Mufasa", "You've been warned, Shenzi!", null, null, null, null, null, new DateTime(1994, 10, 16, 13, 12, 40, 0, DateTimeKind.Utc) },
                    { 49L, 9L, "Nala (cub)", "(To Simba) I thought you were very brave.", null, null, null, null, null, new DateTime(1994, 10, 16, 13, 12, 45, 0, DateTimeKind.Utc) },
                    { 50L, 1L, "Mufasa", "Simba, you deliberately disobeyed me! You could have been killed! And what's worse, you put Nala in danger! Do you understand what's at stake? You jeopardized the future of our pride!", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 0, 0, 0, DateTimeKind.Utc) },
                    { 51L, 7L, "Simba (cub)", "I just wanted to show you I could do it! That I could be brave like you!", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 0, 5, 0, DateTimeKind.Utc) },
                    { 52L, 1L, "Mufasa", "I'm only brave when I have to be, when there's no other choice.", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 0, 10, 0, DateTimeKind.Utc) },
                    { 53L, 7L, "Simba (cub)", "But... You're not scared of anything.", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 0, 15, 0, DateTimeKind.Utc) },
                    { 54L, 1L, "Mufasa", "I was today...", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 0, 20, 0, DateTimeKind.Utc) },
                    { 55L, 7L, "Simba (cub)", "You were?!", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 0, 25, 0, DateTimeKind.Utc) },
                    { 56L, 1L, "Mufasa", "Yes! I thought I'd might lose you.", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 0, 30, 0, DateTimeKind.Utc) },
                    { 57L, 7L, "Simba (cub)", "I guess even kings get scared, huh?!", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 0, 35, 0, DateTimeKind.Utc) },
                    { 58L, 1L, "Mufasa", "More than you could ever know.", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 0, 40, 0, DateTimeKind.Utc) },
                    { 59L, 7L, "Simba (cub)", "But guess what?", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 0, 45, 0, DateTimeKind.Utc) },
                    { 60L, 1L, "Mufasa", "What?", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 0, 50, 0, DateTimeKind.Utc) },
                    { 61L, 7L, "Simba (cub)", "I think those hyenas were even scareder!", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 0, 55, 0, DateTimeKind.Utc) },
                    { 62L, 1L, "Mufasa", "That's 'cause nobody messes with your dad!", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 1, 0, 0, DateTimeKind.Utc) },
                    { 63L, 1L, "Mufasa", "Simba, let me tell you something my father told me. Look at the stars. The great kings of the past look down on us from those stars.", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 5, 0, 0, DateTimeKind.Utc) },
                    { 64L, 7L, "Simba (cub)", "Really?", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 5, 5, 0, DateTimeKind.Utc) },
                    { 65L, 1L, "Mufasa", "Yes! So whenever you feel alone, just remember that those kings will always be up there to guide you. And so will I.", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 5, 10, 0, DateTimeKind.Utc) },
                    { 66L, 7L, "Simba (cub)", "But I can't see them, dad!", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 5, 0, 0, DateTimeKind.Utc) },
                    { 67L, 1L, "Mufasa", "Keep looking son. Keep looking.", null, null, null, null, null, new DateTime(1994, 10, 16, 19, 5, 0, 0, DateTimeKind.Utc) },
                    { 68L, 4L, "Scar", "You fools have stripped you land of every living thing. And yet I send two little cubs your way, and they come back alive!", null, null, null, null, null, new DateTime(1994, 10, 17, 20, 0, 0, 0, DateTimeKind.Utc) },
                    { 69L, 14L, "Kamari", "I guess we'll have to eat you instead.", null, null, null, null, null, new DateTime(1994, 10, 17, 20, 0, 5, 0, DateTimeKind.Utc) },
                    { 70L, 13L, "Shenzi", "What could you possibly offer us?", null, null, null, null, null, new DateTime(1994, 10, 17, 20, 0, 10, 0, DateTimeKind.Utc) },
                    { 71L, 4L, "Scar", "A place where you can fill your bellies. Where everything the light touches is yours for the kill.", null, null, null, null, null, new DateTime(1994, 10, 17, 20, 0, 15, 0, DateTimeKind.Utc) },
                    { 72L, 13L, "Shenzi", "The Pride Lands are not yours to give. The king controls those hunting grounds.", null, null, null, null, null, new DateTime(1994, 10, 17, 20, 0, 20, 0, DateTimeKind.Utc) },
                    { 73L, 4L, "Scar", "That's why we're going to kill him.", null, null, null, null, null, new DateTime(1994, 10, 17, 20, 0, 25, 0, DateTimeKind.Utc) },
                    { 74L, 7L, "Simba (cub)", "My dad was pretty upset with me.", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 0, 0, 0, DateTimeKind.Utc) },
                    { 75L, 4L, "Scar", "That's why we're here Simba. I think I know a way for you to make it up to him. A gift that will make him forget it ever happened.", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 0, 5, 0, DateTimeKind.Utc) },
                    { 76L, 7L, "Simba (cub)", "But he's the king! What could I give him?", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 0, 10, 0, DateTimeKind.Utc) },
                    { 77L, 4L, "Scar", "Your roar!", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 0, 15, 0, DateTimeKind.Utc) },
                    { 78L, 7L, "Simba (cub)", "My roar?", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 0, 20, 0, DateTimeKind.Utc) },
                    { 79L, 4L, "Scar", "Yes! ... Did you hear that? This gorge is where all lions come to find their roar.", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 0, 25, 0, DateTimeKind.Utc) },
                    { 80L, 7L, "Simba (cub)", "All lions? Even my dad?", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 0, 30, 0, DateTimeKind.Utc) },
                    { 81L, 4L, "Scar", "Even Mufasa came here when he was your age. Refused to leave until his roar could be heard above the rim.", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 0, 35, 0, DateTimeKind.Utc) },
                    { 82L, 7L, "Simba (cub)", "All the way up there?", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 0, 40, 0, DateTimeKind.Utc) },
                    { 83L, 4L, "Scar", "That's when you know you've found it! With a little practice, you'll never be called a cub again!", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 0, 45, 0, DateTimeKind.Utc) },
                    { 84L, 7L, "Simba (cub)", "Watch this! (soft cub roar)", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 0, 50, 0, DateTimeKind.Utc) },
                    { 85L, 4L, "Scar", "You'll get it, Simba. Just takes time. I'll check on you later.", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 0, 55, 0, DateTimeKind.Utc) },
                    { 86L, 7L, "Simba (cub)", "Dad will be so proud, won't he?", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 1, 0, 0, DateTimeKind.Utc) },
                    { 87L, 4L, "Scar", "It's a gift he'll never forget...", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 1, 5, 0, DateTimeKind.Utc) },
                    { 88L, 4L, "Scar", "Simba! What have you done?!", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 10, 0, 0, DateTimeKind.Utc) },
                    { 89L, 7L, "Simba (cub)", "It was a stampede! He tried to save me! It was an accident! I didn't mean for it to...", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 10, 5, 0, DateTimeKind.Utc) },
                    { 90L, 4L, "Scar", "Of course you didn't. No one ever means for these things to happen. But the king is dead, and if it weren't for you, he'd still be alive! Your father had such hopes for you, gave you so many chances, and this is how you repay him!", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 10, 10, 0, DateTimeKind.Utc) },
                    { 91L, 7L, "Simba (cub)", "I didn't know! I didn't know!", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 10, 15, 0, DateTimeKind.Utc) },
                    { 92L, 4L, "Scar", "Oh, what will your mother think? A son who causes his father's death! A boy who kills a king!", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 10, 20, 0, DateTimeKind.Utc) },
                    { 93L, 7L, "Simba (cub)", "What am I gonna do?", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 10, 25, 0, DateTimeKind.Utc) },
                    { 94L, 4L, "Scar", "Run. Run away, Simba! Run away and never return!", null, null, null, null, null, new DateTime(1994, 10, 18, 10, 10, 30, 0, DateTimeKind.Utc) },
                    { 95L, 4L, "Scar", "Mufasa's death is a terrible tragedy! The greatest leader the pride has ever known. To lose a brother, such a deep, personal loss. And little Simba, who had barely begun to live. A cub whose blood held our future. It's almost too much to endure. I only wish I had gotten to the gorge in time... Been there to save them! And so it is with a heavy heart that I must assume the throne. Mufasa and Simba are gone, which means I am YOUR king! But I must admit: I cannot bear this burden alone, and I will need some help, to ensure the safety of the pride. And so, from the ashes of this tragedy, we shall welcome the dawning of a new era, a great and glorious future!", null, null, null, null, null, new DateTime(1994, 10, 18, 11, 0, 0, 0, DateTimeKind.Utc) },
                    { 96L, 12L, "Pumbaa", "Oh no! It's a little lion!", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 0, 0, 0, DateTimeKind.Utc) },
                    { 97L, 7L, "Simba (cub)", "Who are you?", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 0, 5, 0, DateTimeKind.Utc) },
                    { 98L, 11L, "Timon", "We're the guys who saved your life. Risked everything. Fought off angry vultures!", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 0, 10, 0, DateTimeKind.Utc) },
                    { 99L, 12L, "Pumbaa", "Hordes of them. Flocks. I'm Pumbaa. This is Timon.", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 0, 15, 0, DateTimeKind.Utc) },
                    { 100L, 11L, "Timon", "So, how are you in as few words as possible?", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 0, 20, 0, DateTimeKind.Utc) },
                    { 101L, 7L, "Simba (cub)", "I did something terrible... I don't wanna talk about it...", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 0, 25, 0, DateTimeKind.Utc) },
                    { 102L, 12L, "Pumbaa", "Look, kid, we've all made mistakes! Uh, there must be something we can do, right?", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 0, 30, 0, DateTimeKind.Utc) },
                    { 103L, 7L, "Simba (cub)", "Not unless you can change the past.", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 0, 35, 0, DateTimeKind.Utc) },
                    { 104L, 11L, "Timon", "You know what you can change? The future! That's our specialty!", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 0, 40, 0, DateTimeKind.Utc) },
                    { 105L, 7L, "Simba (cub)", "How can you change something that hasn't happened?", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 0, 45, 0, DateTimeKind.Utc) },
                    { 106L, 11L, "Timon", "Well, to change the future, you got to put your past behind you.", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 0, 50, 0, DateTimeKind.Utc) },
                    { 107L, 12L, "Pumbaa", "Way behind!", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 0, 55, 0, DateTimeKind.Utc) },
                    { 108L, 11L, "Timon", "Look, kid! Bad things happen, and you can't do anything about it, right?", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 1, 0, 0, DateTimeKind.Utc) },
                    { 109L, 7L, "Simba (cub)", "Right...", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 1, 5, 0, DateTimeKind.Utc) },
                    { 110L, 11L, "Timon", "WRONG! When the world turns the back you, you turn your back on the world!", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 1, 10, 0, DateTimeKind.Utc) },
                    { 111L, 12L, "Pumbaa", "And only embrace what's next!", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 1, 15, 0, DateTimeKind.Utc) },
                    { 112L, 11L, "Timon", "And turn the what into so what?", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 1, 20, 0, DateTimeKind.Utc) },
                    { 113L, 7L, "Simba (cub)", "Well, that's not what I was taught.", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 1, 25, 0, DateTimeKind.Utc) },
                    { 114L, 11L, "Timon", "Well, then maybe you need a new lesson. Repeat after me, kid: Hakuna matata.", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 1, 30, 0, DateTimeKind.Utc) },
                    { 115L, 7L, "Simba (cub)", "What?!", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 1, 35, 0, DateTimeKind.Utc) },
                    { 116L, 12L, "Pumbaa", "Hakuna matata", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 1, 40, 0, DateTimeKind.Utc) },
                    { 117L, 11L, "Timon", "Hakuna matata!", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 1, 45, 0, DateTimeKind.Utc) },
                    { 118L, 12L, "Pumbaa", "Most people get a bigger reaction when they say if the first... Okay, well anyway. Hakuna matata. It means no worries.", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 1, 50, 0, DateTimeKind.Utc) },
                    { 119L, 11L, "Timon", "Hakuna matata. What a wonderful phrase.", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 1, 55, 0, DateTimeKind.Utc) },
                    { 120L, 12L, "Pumbaa", "Hakuna matata. It ain't no passing craze.", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 2, 0, 0, DateTimeKind.Utc) },
                    { 121L, 11L, "Timon", "It means no worries for the rest of your days. It's our problem free philosophy. Hakuna matata.", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 2, 5, 0, DateTimeKind.Utc) },
                    { 122L, 7L, "Simba (cub)", "It means no worries for the rest of your days. It's our problem free philosophy. Hakuna matata.", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 2, 10, 0, DateTimeKind.Utc) },
                    { 123L, 11L, "Timon", "Welcome to our humble home.", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 30, 0, 0, DateTimeKind.Utc) },
                    { 124L, 7L, "Simba (cub)", "It's beautiful!", null, null, null, null, null, new DateTime(1994, 10, 20, 11, 30, 5, 0, DateTimeKind.Utc) },
                    { 125L, 3L, "Sarabi", "The morning report, Zazu.", null, null, null, null, null, new DateTime(1995, 9, 1, 9, 0, 0, 0, DateTimeKind.Utc) },
                    { 126L, 6L, "Zazu", "Your Majesty, the Pride Lands are in imminent danger. The hyenas are chasing of the last of the herds.", null, null, null, null, null, new DateTime(1995, 9, 1, 9, 0, 5, 0, DateTimeKind.Utc) },
                    { 127L, 10L, "Nala", "We have to do something, Sarabi! We have to fight!", null, null, null, null, null, new DateTime(1995, 9, 1, 9, 0, 10, 0, DateTimeKind.Utc) },
                    { 128L, 3L, "Sarabi", "Nala, Scar is the king.", null, null, null, null, null, new DateTime(1995, 9, 1, 9, 0, 15, 0, DateTimeKind.Utc) },
                    { 129L, 10L, "Nala", "But you are our QUEEN! We should leave before it's too late!", null, null, null, null, null, new DateTime(1995, 9, 1, 9, 0, 20, 0, DateTimeKind.Utc) },
                    { 130L, 3L, "Sarabi", "We must all stay together and protect the Pride Lands. This is our home. we must never abandon it.", null, null, null, null, null, new DateTime(1995, 9, 1, 9, 0, 25, 0, DateTimeKind.Utc) },
                    { 131L, 10L, "Nala", "This isn't the home I remember.", null, null, null, null, null, new DateTime(1995, 9, 1, 9, 0, 30, 0, DateTimeKind.Utc) },
                    { 132L, 3L, "Sarabi", "Our time will come, Nala! Be patient.", null, null, null, null, null, new DateTime(1995, 9, 1, 9, 0, 35, 0, DateTimeKind.Utc) },
                    { 133L, 6L, "Zazu", "Just what do you think you are doing, young lady?", null, null, null, null, null, new DateTime(1995, 9, 1, 21, 0, 0, 0, DateTimeKind.Utc) },
                    { 134L, 10L, "Nala", "Go away, Zazu. I'm going to find help.", null, null, null, null, null, new DateTime(1995, 9, 1, 21, 0, 5, 0, DateTimeKind.Utc) },
                    { 135L, 6L, "Zazu", "I will very much not go away. I am sworn to protect you and must order you back to bed.", null, null, null, null, null, new DateTime(1995, 9, 1, 21, 0, 10, 0, DateTimeKind.Utc) },
                    { 136L, 10L, "Nala", "I don't need protecting anymore.", null, null, null, null, null, new DateTime(1995, 9, 1, 21, 0, 15, 0, DateTimeKind.Utc) },
                    { 137L, 5L, "Rafiki", "Simba is alive!!!", null, null, null, null, null, new DateTime(1995, 9, 2, 9, 0, 0, 0, DateTimeKind.Utc) },
                    { 138L, 11L, "Timon", "RUN FOR YOUR LIVES! RUN PUMBAA, RUN!!!", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 0, 0, 0, DateTimeKind.Utc) },
                    { 139L, 12L, "Pumbaa", "Timon, help!!!", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 1, 0, 0, DateTimeKind.Utc) },
                    { 140L, 11L, "Timon", "Pumbaa!!!", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 2, 0, 0, DateTimeKind.Utc) },
                    { 141L, 12L, "Pumbaa", "I'M GONNA DIE!!!", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 3, 0, 0, DateTimeKind.Utc) },
                    { 142L, 8L, "Simba", "Nala!?", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 5, 0, 0, DateTimeKind.Utc) },
                    { 143L, 10L, "Nala", "Simba!? Is that really you?", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 5, 5, 0, DateTimeKind.Utc) },
                    { 144L, 8L, "Simba", "Yeah!!! It's me, Simba!", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 5, 10, 0, DateTimeKind.Utc) },
                    { 145L, 10L, "Nala", "Where have you been? I thought you were dead!", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 5, 15, 0, DateTimeKind.Utc) },
                    { 146L, 12L, "Pumbaa", "I thought you were gonna eat me.", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 5, 20, 0, DateTimeKind.Utc) },
                    { 147L, 11L, "Timon", "How do you two know each other?", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 5, 25, 0, DateTimeKind.Utc) },
                    { 148L, 8L, "Simba", "Timon, Pumbaa, I want you to meet my best friend, Nala!", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 5, 30, 0, DateTimeKind.Utc) },
                    { 149L, 10L, "Nala", "Simba, we need to leave! Scar has taken over with the hyenas. You have to take your place as king.", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 5, 35, 0, DateTimeKind.Utc) },
                    { 150L, 11L, "Timon", "King?! Simba?! ", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 5, 40, 0, DateTimeKind.Utc) },
                    { 151L, 10L, "Nala", "Seing you again, you don't know what this will mean to everyone, what this means to me! You have to come home.", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 5, 45, 0, DateTimeKind.Utc) },
                    { 152L, 8L, "Simba", "This IS my home. Please stay. This place is incredible. I know you'll love it.", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 5, 50, 0, DateTimeKind.Utc) },
                    { 153L, 10L, "Nala", "I can't.", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 5, 55, 0, DateTimeKind.Utc) },
                    { 154L, 8L, "Simba", "C'mon! At least let me show you around.", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 6, 0, 0, DateTimeKind.Utc) },
                    { 155L, 10L, "Nala", "Where are you going?!", null, null, null, null, null, new DateTime(1995, 9, 3, 9, 6, 5, 0, DateTimeKind.Utc) },
                    { 156L, 10L, "Nala", "Simba, it's so beautiful.", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 0, 0, 0, DateTimeKind.Utc) },
                    { 157L, 8L, "Simba", "I told you. Isn't it great here? You know, maybe it could be like this forever.", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 0, 5, 0, DateTimeKind.Utc) },
                    { 158L, 10L, "Nala", "It's amazing. But there's something I don't understand: If you've been alive all this time, why haven't you come home? We've really needed you.", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 0, 10, 0, DateTimeKind.Utc) },
                    { 159L, 8L, "Simba", "They're fine, all right? Nobody needs me.", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 0, 15, 0, DateTimeKind.Utc) },
                    { 160L, 10L, "Nala", "You're the king!", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 0, 20, 0, DateTimeKind.Utc) },
                    { 161L, 8L, "Simba", "Nala, SCAR is the king.", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 0, 25, 0, DateTimeKind.Utc) },
                    { 162L, 10L, "Nala", "Simba, he's decimated the Pride Lands! There's no food, no water...", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 0, 30, 0, DateTimeKind.Utc) },
                    { 163L, 8L, "Simba", "There's nothing I can do.", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 0, 35, 0, DateTimeKind.Utc) },
                    { 164L, 10L, "Nala", "What about your mother? This is your responsibility! You need to chalenge Scar!", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 0, 40, 0, DateTimeKind.Utc) },
                    { 165L, 8L, "Simba", "I can't go back! EVER!", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 0, 45, 0, DateTimeKind.Utc) },
                    { 166L, 10L, "Nala", "Why? Because of what happened at the gorge? Scar told us that...", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 0, 50, 0, DateTimeKind.Utc) },
                    { 167L, 8L, "Simba", "You wouldn't understand... None of it matters, okay? Hakuna Matata.", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 0, 55, 0, DateTimeKind.Utc) },
                    { 168L, 10L, "Nala", "What?!", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 1, 0, 0, DateTimeKind.Utc) },
                    { 169L, 8L, "Simba", "It's something I learned out here, okay? You see, sometimes bad things happen, and there's nothing you can do about it. So, why worry?", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 1, 5, 0, DateTimeKind.Utc) },
                    { 170L, 10L, "Nala", "Why worry?! What happened to you?! You're not the Simba I remember!", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 1, 10, 0, DateTimeKind.Utc) },
                    { 171L, 8L, "Simba", "And I never will be, are you satisfied?", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 1, 15, 0, DateTimeKind.Utc) },
                    { 172L, 10L, "Nala", "No, I'm disappointed.", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 1, 20, 0, DateTimeKind.Utc) },
                    { 173L, 8L, "Simba", "You know, now you're starting to sound like my father.", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 1, 25, 0, DateTimeKind.Utc) },
                    { 174L, 10L, "Nala", "Good! I'm glad one of us does!", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 1, 30, 0, DateTimeKind.Utc) },
                    { 175L, 8L, "Simba", "YOU HAVE NO IDEA WHAT I'VE BEEN THROUGH!!!", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 1, 35, 0, DateTimeKind.Utc) },
                    { 176L, 10L, "Nala", "I came here looking for help. I guess I made a mistake. Goodbye, Simba...", null, null, null, null, null, new DateTime(1995, 9, 3, 10, 1, 40, 0, DateTimeKind.Utc) },
                    { 177L, 8L, "Simba", "Go away!", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 0, 0, 0, DateTimeKind.Utc) },
                    { 178L, 5L, "Rafiki", "Going away will not answer the question!", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 0, 5, 0, DateTimeKind.Utc) },
                    { 179L, 8L, "Simba", "What question? Who are you?", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 0, 10, 0, DateTimeKind.Utc) },
                    { 180L, 5L, "Rafiki", "I know exactly who I am. The question is: Who are you?", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 0, 15, 0, DateTimeKind.Utc) },
                    { 181L, 8L, "Simba", "I'm nobody. So leave me alone, all right?", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 0, 20, 0, DateTimeKind.Utc) },
                    { 182L, 5L, "Rafiki", "Everybody is somebody. Even a nobody.", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 0, 25, 0, DateTimeKind.Utc) },
                    { 183L, 8L, "Simba", "Yeah, I think you're confused.", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 0, 30, 0, DateTimeKind.Utc) },
                    { 184L, 5L, "Rafiki", "I am confused? You don't even know who you are!", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 0, 35, 0, DateTimeKind.Utc) },
                    { 185L, 8L, "Simba", "Oh! And I suppose you do?", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 0, 40, 0, DateTimeKind.Utc) },
                    { 186L, 5L, "Rafiki", "I held the son of Mufasa.", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 0, 45, 0, DateTimeKind.Utc) },
                    { 187L, 8L, "Simba", "You knew my father?", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 0, 50, 0, DateTimeKind.Utc) },
                    { 188L, 5L, "Rafiki", "Correction: I KNOW your father.", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 0, 55, 0, DateTimeKind.Utc) },
                    { 189L, 8L, "Simba", "He died a long time ago.", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 1, 0, 0, DateTimeKind.Utc) },
                    { 190L, 5L, "Rafiki", "He's alive!!! And I can take you to him. Follow me, I will show you! If you can keep up!", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 1, 5, 0, DateTimeKind.Utc) },
                    { 191L, 8L, "Simba", "Wait!", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 1, 10, 0, DateTimeKind.Utc) },
                    { 192L, 5L, "Rafiki", "Come... Your father is waiting... Do you see him?", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 30, 0, 0, DateTimeKind.Utc) },
                    { 193L, 8L, "Simba", "I don't see anything.", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 30, 5, 0, DateTimeKind.Utc) },
                    { 194L, 5L, "Rafiki", "Look closer... You see? He lives in you.", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 30, 10, 0, DateTimeKind.Utc) },
                    { 195L, 2L, "Mufasa (spirit)", "Simba.", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 30, 15, 0, DateTimeKind.Utc) },
                    { 196L, 8L, "Simba", "Dad?", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 30, 20, 0, DateTimeKind.Utc) },
                    { 197L, 2L, "Mufasa (spirit)", "Simba, you must take your place in the circle of life.", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 30, 25, 0, DateTimeKind.Utc) },
                    { 198L, 8L, "Simba", "I can't.", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 30, 30, 0, DateTimeKind.Utc) },
                    { 199L, 2L, "Mufasa (spirit)", "You must remember who you are: The one true king.", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 30, 35, 0, DateTimeKind.Utc) },
                    { 200L, 8L, "Simba", "I'm sorry. I don't know how to be like you.", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 30, 40, 0, DateTimeKind.Utc) },
                    { 201L, 2L, "Mufasa (spirit)", "As king, I was most proud of one thing: Having you as my son.", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 30, 45, 0, DateTimeKind.Utc) },
                    { 202L, 8L, "Simba", "That was a long time ago...", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 30, 50, 0, DateTimeKind.Utc) },
                    { 203L, 2L, "Mufasa (spirit)", "No, Simba. That is forever.", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 30, 55, 0, DateTimeKind.Utc) },
                    { 204L, 8L, "Simba", "Please, don't leave me again.", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 31, 0, 0, DateTimeKind.Utc) },
                    { 205L, 2L, "Mufasa (spirit)", "I never left you. And never will. Remember who you are. Remember.", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 31, 5, 0, DateTimeKind.Utc) },
                    { 206L, 5L, "Rafiki", "And so, I ask again: Who are you?", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 31, 10, 0, DateTimeKind.Utc) },
                    { 207L, 8L, "Simba", "... I am Simba. Son of Mufasa! (ROAR)", null, null, null, null, null, new DateTime(1995, 9, 3, 18, 31, 15, 0, DateTimeKind.Utc) },
                    { 208L, 10L, "Nala", "Simba?", null, null, null, null, null, new DateTime(1995, 9, 4, 9, 0, 0, 0, DateTimeKind.Utc) },
                    { 209L, 8L, "Simba", "C'mon! What are you waiting for? Let's go home!", null, null, null, null, null, new DateTime(1995, 9, 4, 9, 0, 5, 0, DateTimeKind.Utc) },
                    { 210L, 8L, "Simba", "I didn't wanna believe you.", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 0, 0, 0, DateTimeKind.Utc) },
                    { 211L, 10L, "Nala", "So, what are you gonna do?", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 0, 5, 0, DateTimeKind.Utc) },
                    { 212L, 8L, "Simba", "My father once told me to protect everything the light touches. If I don't fight for it, who will?", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 0, 10, 0, DateTimeKind.Utc) },
                    { 213L, 10L, "Nala", "I will.", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 0, 15, 0, DateTimeKind.Utc) },
                    { 214L, 8L, "Simba", "It's going to be dangerous.", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 0, 20, 0, DateTimeKind.Utc) },
                    { 215L, 10L, "Nala", "Danger? Ha! I laugh in the face of danger!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 0, 25, 0, DateTimeKind.Utc) },
                    { 216L, 6L, "Zazu", "It can't be!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 0, 30, 0, DateTimeKind.Utc) },
                    { 217L, 8L, "Simba", "Hello Zazu!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 0, 35, 0, DateTimeKind.Utc) },
                    { 218L, 6L, "Zazu", "Your majesty! Welcome home!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 0, 40, 0, DateTimeKind.Utc) },
                    { 219L, 12L, "Pumbaa", "We're here!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 0, 45, 0, DateTimeKind.Utc) },
                    { 220L, 11L, "Timon", "Everyone, calm down! We're here!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 0, 50, 0, DateTimeKind.Utc) },
                    { 221L, 12L, "Pumbaa", "The backup has arrived!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 0, 55, 0, DateTimeKind.Utc) },
                    { 222L, 4L, "Scar", "Sarabi, why put yourself through this? All you have to do is be my queen! You're suffering for what? The memory of a life you once knew? A king you once loved? I tried to make you understand what a TRUE king can be.", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 30, 0, 0, DateTimeKind.Utc) },
                    { 223L, 3L, "Sarabi", "Scar, a true king's power is his compassion.", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 30, 5, 0, DateTimeKind.Utc) },
                    { 224L, 4L, "Scar", "I AM TEN TIMES THE KING MUFASA WAS!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 30, 10, 0, DateTimeKind.Utc) },
                    { 225L, 3L, "Sarabi", "You are nothing compared to Mufasa!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 30, 15, 0, DateTimeKind.Utc) },
                    { 226L, 2L, "Mufasa (spirit)", "(ROAR)", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 30, 20, 0, DateTimeKind.Utc) },
                    { 227L, 4L, "Scar", "Mufasa?! It can't be!!!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 30, 25, 0, DateTimeKind.Utc) },
                    { 228L, 2L, "Mufasa (spirit)", "GET AWAY FROM MY MOTHER!!!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 30, 30, 0, DateTimeKind.Utc) },
                    { 229L, 3L, "Sarabi", "Simba! You're alive?! How can that be?!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 30, 35, 0, DateTimeKind.Utc) },
                    { 230L, 8L, "Simba", "I'm here, mother. I'm home.", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 30, 40, 0, DateTimeKind.Utc) },
                    { 231L, 4L, "Scar", "Simba, I'm so happy to see you... alive.", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 30, 45, 0, DateTimeKind.Utc) },
                    { 232L, 8L, "Simba", "Give me one good reason why I shouldn't rip you apart!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 30, 50, 0, DateTimeKind.Utc) },
                    { 233L, 4L, "Scar", "I can give you more than one. You see, the hyenas think I'm king.", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 30, 55, 0, DateTimeKind.Utc) },
                    { 234L, 10L, "Nala", "Well, we don't! Your reign is over, Scar! Simba is the rightful king! If you wanna get him, you have to get through us! Are you with me, lions?", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 31, 0, 0, DateTimeKind.Utc) },
                    { 235L, 8L, "Simba", "The choice is yours, Scar. Step down or fight.", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 31, 5, 0, DateTimeKind.Utc) },
                    { 236L, 4L, "Scar", "Must this all end in violence? I'd hate to be responsible for the death of a family member. To feel the shame of knowing I took the life of someone I love.", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 31, 10, 0, DateTimeKind.Utc) },
                    { 237L, 8L, "Simba", "I put all that behind me.", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 31, 15, 0, DateTimeKind.Utc) },
                    { 238L, 4L, "Scar", "But have they put it behind them? Do your faithful subjects know what you've done?", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 31, 20, 0, DateTimeKind.Utc) },
                    { 239L, 3L, "Sarabi", "What is he talking about?", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 31, 25, 0, DateTimeKind.Utc) },
                    { 240L, 4L, "Scar", "So you haven't told them your little secret? Well, Simba... now's your chance to confess. Tell them who's responsible for Mufasa's death!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 31, 30, 0, DateTimeKind.Utc) },
                    { 241L, 8L, "Simba", "... It was me...", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 31, 35, 0, DateTimeKind.Utc) },
                    { 242L, 3L, "Sarabi", "It's not true. Tell me it's not true.", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 31, 40, 0, DateTimeKind.Utc) },
                    { 243L, 8L, "Simba", "It's true. I'm sorry.", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 31, 45, 0, DateTimeKind.Utc) },
                    { 244L, 4L, "Scar", "He admits it! Murderer!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 31, 50, 0, DateTimeKind.Utc) },
                    { 245L, 8L, "Simba", "No! No! It was an accident!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 31, 55, 0, DateTimeKind.Utc) },
                    { 246L, 4L, "Scar", "If it weren't for you the king would be alive! It's your fault he's dead! Do you deny it?", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 32, 0, 0, DateTimeKind.Utc) },
                    { 247L, 8L, "Simba", "I'm not a murderer!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 32, 5, 0, DateTimeKind.Utc) },
                    { 248L, 4L, "Scar", "We should believe the son who takes the life of a father? We should believe the son who takes the life of a king? A son who abandons his mother?", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 32, 10, 0, DateTimeKind.Utc) },
                    { 249L, 8L, "Simba", "No, I'm...", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 32, 15, 0, DateTimeKind.Utc) },
                    { 250L, 4L, "Scar", "You're what? Say it! Are you the king?", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 32, 20, 0, DateTimeKind.Utc) },
                    { 251L, 8L, "Simba", "No. No, I'm...", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 32, 25, 0, DateTimeKind.Utc) },
                    { 252L, 4L, "Scar", "ARE YOU THE KING?", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 32, 30, 0, DateTimeKind.Utc) },
                    { 253L, 8L, "Simba", "No, I'm...", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 32, 35, 0, DateTimeKind.Utc) },
                    { 254L, 4L, "Scar", "You're what? SAY IT!!!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 32, 40, 0, DateTimeKind.Utc) },
                    { 255L, 8L, "Simba", "I'm... I'm nothing...", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 32, 45, 0, DateTimeKind.Utc) },
                    { 256L, 4L, "Scar", "Then BOW to you king!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 32, 50, 0, DateTimeKind.Utc) },
                    { 257L, 3L, "Sarabi", "Simba!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 32, 55, 0, DateTimeKind.Utc) },
                    { 258L, 4L, "Scar", "This looks familiar. Where have I seen this before? Oh, yes! I remember! This is the way Mufasa looked before he died. I looked down... saw the fear in his eyes. And here's my little secret: I... killed... Mufasa!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 33, 0, 0, DateTimeKind.Utc) },
                    { 259L, 8L, "Simba", "MY FATHER! YOUR OWN BROTHER! HOW COULD YOU?!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 33, 5, 0, DateTimeKind.Utc) },
                    { 260L, 4L, "Scar", "First he kills Mufasa! Now he wants to kill me!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 33, 10, 0, DateTimeKind.Utc) },
                    { 261L, 8L, "Simba", "YOU KILLED HIM! TELL THEM THE TRUTH!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 33, 15, 0, DateTimeKind.Utc) },
                    { 262L, 4L, "Scar", "Don't believe his lies!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 33, 20, 0, DateTimeKind.Utc) },
                    { 263L, 3L, "Sarabi", "Scar... You told us you didn't get to the gorge in time...", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 33, 25, 0, DateTimeKind.Utc) },
                    { 264L, 4L, "Scar", "That's true!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 33, 30, 0, DateTimeKind.Utc) },
                    { 265L, 3L, "Sarabi", "Then how did you see the look in Mufasa's eyes?", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 33, 35, 0, DateTimeKind.Utc) },
                    { 266L, 8L, "Simba", "MURDERER!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 33, 40, 0, DateTimeKind.Utc) },
                    { 267L, 4L, "Scar", "HYENAS, KILL THEM ALL!!!", null, null, null, null, null, new DateTime(1995, 9, 6, 15, 33, 45, 0, DateTimeKind.Utc) },
                    { 268L, 8L, "Simba", "It's over Scar!", null, null, null, null, null, new DateTime(1995, 9, 6, 16, 0, 0, 0, DateTimeKind.Utc) },
                    { 269L, 4L, "Scar", "Have mercy, I beg you!", null, null, null, null, null, new DateTime(1995, 9, 6, 16, 0, 5, 0, DateTimeKind.Utc) },
                    { 270L, 8L, "Simba", "Mercy? After what you did?", null, null, null, null, null, new DateTime(1995, 9, 6, 16, 0, 10, 0, DateTimeKind.Utc) },
                    { 271L, 4L, "Scar", "It was the hyenas! Those revolting scavengers made me do it! I was planning on killing them all!", null, null, null, null, null, new DateTime(1995, 9, 6, 16, 0, 15, 0, DateTimeKind.Utc) },
                    { 272L, 8L, "Simba", "You fooled the hyenas! Just like you fooled me!", null, null, null, null, null, new DateTime(1995, 9, 6, 16, 0, 20, 0, DateTimeKind.Utc) },
                    { 273L, 4L, "Scar", "Simba... you wouldn't kill your only uncle!", null, null, null, null, null, new DateTime(1995, 9, 6, 16, 0, 25, 0, DateTimeKind.Utc) },
                    { 274L, 8L, "Simba", "No, Scar! I'm not like you!", null, null, null, null, null, new DateTime(1995, 9, 6, 16, 0, 30, 0, DateTimeKind.Utc) },
                    { 275L, 4L, "Scar", "Oh, Simba... you are truly noble! And I will make it up to you! Just tell me how I can prove myself. Tell me what you want me to do.", null, null, null, null, null, new DateTime(1995, 9, 6, 16, 0, 35, 0, DateTimeKind.Utc) },
                    { 276L, 8L, "Simba", "Run. Run away, Scar. Run away and never return.", null, null, null, null, null, new DateTime(1995, 9, 6, 16, 0, 40, 0, DateTimeKind.Utc) },
                    { 277L, 4L, "Scar", "... Yes... Of course... As you wish... your majesty", null, null, null, null, null, new DateTime(1995, 9, 6, 16, 0, 45, 0, DateTimeKind.Utc) },
                    { 278L, 8L, "Simba", "You can't win Scar!", null, null, null, null, null, new DateTime(1995, 9, 6, 16, 0, 50, 0, DateTimeKind.Utc) },
                    { 279L, 4L, "Scar", "This is my kingdom! My destiny!", null, null, null, null, null, new DateTime(1995, 9, 6, 16, 0, 55, 0, DateTimeKind.Utc) },
                    { 280L, 8L, "Simba", "I defeated Scar!", null, null, null, null, null, new DateTime(1995, 9, 6, 16, 5, 0, 0, DateTimeKind.Utc) },
                    { 281L, 4L, "Scar", "My friends. It will take some time, but together we will build our army.", null, null, null, null, null, new DateTime(1995, 9, 6, 19, 30, 0, 0, DateTimeKind.Utc) },
                    { 282L, 14L, "Kamari", "Friends, huh? I thought you said we were revolting scavengers! Yeah, that you wanted to kill us!", null, null, null, null, null, new DateTime(1995, 9, 6, 19, 30, 5, 0, DateTimeKind.Utc) },
                    { 283L, 4L, "Scar", "No! No, let me explain! I was trying to fool him! We will rule together!", null, null, null, null, null, new DateTime(1995, 9, 6, 19, 30, 10, 0, DateTimeKind.Utc) },
                    { 284L, 13L, "Shenzi", "There's only one true thing you ever said, Scar: A hyena's belly is never full!", null, null, null, null, null, new DateTime(1995, 9, 6, 19, 30, 15, 0, DateTimeKind.Utc) },
                    { 285L, 6L, "Zazu", "Your majesty!", null, null, null, null, null, new DateTime(1995, 9, 7, 9, 0, 0, 0, DateTimeKind.Utc) },
                    { 286L, 2L, "Mufasa (spirit)", "Remember!", null, null, null, null, null, new DateTime(1995, 9, 7, 9, 0, 5, 0, DateTimeKind.Utc) },
                    { 287L, 8L, "Simba", "(ROAR)", null, null, null, null, null, new DateTime(1995, 9, 7, 9, 0, 10, 0, DateTimeKind.Utc) },
                    { 288L, 10L, "Nala", "(ROAR)", null, null, null, null, null, new DateTime(1995, 9, 7, 9, 0, 15, 0, DateTimeKind.Utc) },
                    { 289L, 3L, "Sarabi", "(ROAR)", null, null, null, null, null, new DateTime(1995, 9, 7, 9, 0, 20, 0, DateTimeKind.Utc) },
                    { 290L, 8L, "Simba", "Nala gave birth to a cub!", null, null, null, null, null, new DateTime(1995, 12, 27, 9, 0, 20, 0, DateTimeKind.Utc) }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Publications_AuthorId",
                table: "Publications",
                column: "AuthorId");

            migrationBuilder.CreateIndex(
                name: "IX_Publications_OriginalPostId",
                table: "Publications",
                column: "OriginalPostId");

            migrationBuilder.CreateIndex(
                name: "IX_Users_Username",
                table: "Users",
                column: "Username",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Publications");

            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
